### PR TITLE
Fixed the `release.yml` workflow file to install snapcraft before building to avoid Ubuntu Error!

### PR DESCRIPTION
**Pull request by Rajdeep-TG**
Dear Patrick,
  I have edited the `release.yml` workflow file located at `.github/workflows/release.yml` to install **Snapcraft** before building to avoid the produced errors I saw in your actions's logs.

### CODE REVIEW

**Comment by Patrick-web** [comment]
Thanks a lot. Let me set a name for snapcraft.

**Comment by Rajdeep-TG** [comment]
Could I help you with it ?

**Comment by Patrick-web** [comment]
I've just created it. Its electron-store like sudo snap install electron-store. Are you a javascript developer?

**Comment by Patrick-web** [comment]
But I haven't uploaded a build yet

**Comment by Rajdeep-TG** [comment]
I am a JavaScript and Python Developer and I have experience with Snapcraft.

**Comment by Rajdeep-TG** [comment]
I am interested to collaborate with you in this project.

**Pull request merged**
